---
:concurrency: 5
:max_retries: 8
:verbose: true
staging:
  :concurrency: 10
production:
  :concurrency: <%= ENV.fetch('RAILS_MAX_THREADS', '20').to_i - 2  %>
:queues:
  - ["external_system_ccd", 10]
  - ["external_system_ccd_callbacks", 4]
  - ["sidekiq_alive", 3]
  - ["external_system_ccd_multiples", 1]
